---
### main.yml - common role for an OpenShift Origin deployment 
#
# Ansible playbook to deploy OpenShift Origin using nightly builds
#

# Setup repos
- name: Setup OpenShift Origin Nightly Repo
  template: src=openshift-origin-nightly.repo.j2
            dest=/etc/yum.repos.d/openshift-origin-nightly.repo
  when: oo_nightly == "true"
- name: Setup OpenShift Origin Nightly Dependencies Repo
  template: src=openshift-origin-nightly-deps.repo.j2
            dest=/etc/yum.repos.d/openshift-origin-nightly-deps.repo
  when: oo_nightly == "true"

- name: Setup OpenShift Origin Stable
  template: src=openshift-origin-stable.repo.j2
            dest=/etc/yum.repos.d/openshift-origin-stable.repo
  when: oo_stable == "true"
- name: Setup OpenShift Origin Stable Dependencies Repo
  template: src=openshift-origin-stable-deps.repo.j2
            dest=/etc/yum.repos.d/openshift-origin-stable-deps.repo
  when: oo_stable == "true"

# SELinux Stuff 
- name: SELinux Enforcing (Targeted)
  selinux: policy=targeted state=enforcing
- name: Ensure Installed - policycoreutils
  yum: pkg=policycoreutils state=latest
- name: Ensure Installed - policycoreutils-python
  yum: pkg=policycoreutils-python state=latest

# Default firewalld configs
- name: Ensure Install - firewalld
  yum: pkg=firewalld state=latest
- name: Start and Enable firewalld daemon
  service: name=firewalld state=started enabled=yes
  async: 10
  poll: 2


# Ensure NTP installed and configured
- name: Ensure Install - ntpdate
  yum: pkg=ntpdate state=latest
- name: Ensure Install - ntp
  yum: pkg=ntp state=latest
- name: Stop ntp daemon for ntpdate sync
  service: name=ntpd state=stopped
  changed_when: False
- name: Synchronize Clock with ntpdate
  command: /usr/sbin/ntpdate -u {{ ntpserver }}
  changed_when: False
- name: Start and Enable ntp daemon
  service: name=ntpd state=started enabled=yes
  changed_when: False

# Configure dhclient
- name: Configure dhclient for DNS
  template: src=dhclient.conf.j2
            dest="/etc/dhcp/dhclient-{{oo_external_iface}}.conf"
            backup=yes
